Age verification rus
cscart/docs pull request #52
Opened 2021-05-12 13:23 UTC by Anastasiaposm

Age verification articles translated into Russian.

2021-05-12 14:22 UTC, Anastasiaposm commented
Age verification and customers also bought articles translated into Russian + corrections in age verification

2021-05-14 05:52 UTC, c-a-t requested changes
Прошёлся по всем текстам, написал о том, что бросилось в глаза. Думаю, если это исравить, то перевод можно считать готовым.

2021-05-14 05:52 UTC, c-a-t commented on ru/user_guide/addons/age_verification/age_verification.rst
> +*   Найдите модуль **Ограничение по возрасту** нажмите **Установить**.
По-моему тут пропущен "и". Без него предложение выглядит странно.

2021-05-14 05:52 UTC, c-a-t commented on ru/user_guide/addons/age_verification/age_verification.rst
> +    *   **Предупреждение** — напечатайте текст, который увидит покупатель, если его возраст несоответсвует заданному допустимому возрасту.
Здесь ведь вроде "не" с глаголом?

2021-05-14 05:52 UTC, c-a-t commented on ru/user_guide/addons/age_verification/age_verification.rst
> +*   В панели управления выберите раздел **Модули → Управление модулями**.
Мы используем соответствие "administration panel" или "admin panel" = "панель администратора"

2021-05-14 05:52 UTC, c-a-t commented on ru/user_guide/addons/age_verification/age_verification.rst
> +Если у вас уже установлен данный модуль, необходимо изменить его статус на *Вкл.* нажатием кнопки *Активировать*.
Тут возникла проблема на нашей стороне. На демке сейчас действительно "Активировать", но там будет кнопка "Включить". А поля "Статус" вообще не будет. Т.е. можно просто написать "необходимо убедиться, что он включен".

В отчёте по переводу можно оставить старый вариант ;-)

2021-05-14 05:52 UTC, c-a-t commented on ru/user_guide/addons/age_verification/age_verification.rst
> +    *   **Проверка возраста** — поставьте галочку в строке.
В оригинале "tick the checkbox to enable the add-on". Т.е. я не вижу тут "в строке". Можно написать "поставьте галочку, чтобы ограничить доступ по возрасту".

2021-05-14 05:52 UTC, c-a-t commented on ru/user_guide/addons/age_verification/age_verification.rst
> +    Также в профиль покупателя будет добавлено поле **День рождения**. Если покупатель зарегестрирован, то его возраст считается автоматически из профиля.
Слово же вроде "регистрация", а значит наверное "зарегистрирован".

2021-05-14 05:52 UTC, c-a-t commented on ru/user_guide/addons/customers_also_bought/customers_also_bought.rst
> +    Убедитесь, что модуль **С этим товаром часто покупают...** установлен и активирован через вкладку **Модули → Управление модулями**.
"Модули > Управление модулями" а также "Товары > Категории" и т.п. мы в русском языке называем страницами. Вкладка - это переключатель уже внутри страницы (т.е. та же "Создать новый блок").

Будет круто, если во всём пулл-реквесте проверишь и поправишь.

2021-05-14 05:52 UTC, c-a-t commented on ru/user_guide/addons/customers_also_bought/customers_also_bought.rst
> +    *   В графе **Название** напечатайте название блока (Например, *Также куплены*).
Странный перевод названия блока. Если наш клиент создаст такой блок и так назовёт его в магазине, то он запутает своих покупателей. Они зайдут на страницу товара и увидят там "Также куплены" и список товаров, которые они возможно никогда не смотрели и себе в корзину не добавляли.

2021-05-14 05:52 UTC, c-a-t commented on ru/user_guide/addons/customers_also_bought/customers_also_bought.rst
> +    *   Откройте вкладку **Контент** и в выпадающем окне выберите *Также куплены*. Выберите **Макс. число элементов** — количество *также купленных* продуктов, которое отобразится на странице. При не
"также купленных продуктов"

1. Термин "товары".
2. Здесь можно отойти от оригинала. Важнее передать смысл. Что значит "также купленные" товары?

2021-05-14 05:52 UTC, c-a-t commented on ru/user_guide/addons/customers_also_bought/customers_also_bought.rst
> +*   Нажмите на **шестеренку** на созданном блоке (Например, *Также куплены*).
Предолжение не закончено, но в скобках почему-то заглавная буква.

2021-05-14 08:10 UTC, Anastasiaposm commented
Corrections in the customers_also_bought and age_verification articles

2021-05-14 08:10 UTC, closed without merging